import type { DownloadItem } from '../types';

export const initialItemsMixed = (): DownloadItem[] => [
  {
    id: 'i1',
    platform: 'youtube',
    title: 'Building a Type System from Scratch — Compiler Series Ep. 04',
    uploader: 'Low Level Academy',
    duration: '47:12',
    format: 'MP4',
    quality: '1080p',
    size: 184_300_000,
    status: 'downloading',
    downloaded: 78_400_000,
    speed: 4_200_000,
    hue: 210,
    url: 'https://youtu.be/build-type-system',
  },
  {
    id: 'i2',
    platform: 'vimeo',
    title: 'Kinfolk — A Quiet Sunday Morning in Copenhagen',
    uploader: 'Kinfolk Studio',
    duration: '08:34',
    format: 'MP4',
    quality: '1080p',
    size: 412_000_000,
    status: 'queued',
    downloaded: 0,
    speed: 0,
    hue: 30,
    url: 'https://vimeo.com/345678',
  },
  {
    id: 'i3',
    platform: 'youtube',
    title: 'lo-fi hip hop radio — beats to relax/study to',
    uploader: 'Lofi Girl',
    duration: '∞ live',
    format: 'MP3',
    quality: '320kbps',
    size: 12_400_000,
    status: 'completed',
    downloaded: 12_400_000,
    speed: 0,
    hue: 285,
    url: 'https://youtu.be/lofi-radio',
    completedAt: Date.now() - 1000 * 60 * 8,
  },
  {
    id: 'i4',
    platform: 'tiktok',
    title: 'POV: when the espresso machine finally arrives 😤☕',
    uploader: '@cafe.minimo',
    duration: '0:23',
    format: 'MP4',
    quality: '1080p',
    size: 8_200_000,
    status: 'completed',
    downloaded: 8_200_000,
    speed: 0,
    hue: 340,
    url: 'https://tiktok.com/@cafe.minimo/video/123',
    completedAt: Date.now() - 1000 * 60 * 22,
  },
  {
    id: 'i5',
    platform: 'twitch',
    title: 'VOD: Speedrunning Hollow Knight — Any% Glitchless WR Attempts',
    uploader: 'fireb0rn',
    duration: '3:42:08',
    format: 'MP4',
    quality: '720p',
    size: 2_400_000_000,
    status: 'failed',
    downloaded: 320_000_000,
    speed: 0,
    hue: 270,
    url: 'https://twitch.tv/videos/9988776',
    error: 'HTTP 403 — VOD is subscriber-only. Try logging in via cookies file.',
  },
  {
    id: 'i6',
    platform: 'soundcloud',
    title: 'Floating Points — Crush (Live at Printworks, 2024)',
    uploader: 'Floating Points',
    duration: '52:18',
    format: 'MP3',
    quality: '320kbps',
    size: 124_800_000,
    status: 'downloading',
    downloaded: 41_200_000,
    speed: 1_800_000,
    hue: 18,
    url: 'https://soundcloud.com/fp/crush-live',
  },
];
